/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anwarassignment26;

/**
 *
 * @author s201076699
 */
public class anwarAssignment26 extends javax.swing.JFrame {

    /**
     * Creates new form anwarAssignment26
     */
    public anwarAssignment26() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDecimal = new javax.swing.JTextField();
        btnDecToBin = new javax.swing.JButton();
        btnDecToBin1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtBinary = new javax.swing.JTextField();
        btnDecToBin2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnHextToDec = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtHexadecimal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("--NUMBER SYSTEMS--");

        jLabel2.setText("Decimal and Binary");

        jLabel3.setText("Enter a decimal number:");

        btnDecToBin.setText("Dec. To Bin.");
        btnDecToBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecToBinActionPerformed(evt);
            }
        });

        btnDecToBin1.setText("Bin. To Dec.");
        btnDecToBin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecToBin1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter a binary number:");

        btnDecToBin2.setText("Dec. To Hex.");
        btnDecToBin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecToBin2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Enter a decimal number:");

        jLabel6.setText("Decimal and Hexadecimal");

        btnHextToDec.setText("Hex. to Dec.");
        btnHextToDec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHextToDecActionPerformed(evt);
            }
        });

        jLabel7.setText("Enter a hexadecimal number:");

        txtHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHexadecimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtHexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDecToBin1)
                                            .addComponent(btnDecToBin)
                                            .addComponent(btnDecToBin2)
                                            .addComponent(btnHextToDec)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBinary, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(202, 202, 202))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(202, 202, 202)))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(271, 271, 271))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecToBin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBinary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecToBin1))
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecToBin2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHexadecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHextToDec))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecToBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecToBinActionPerformed
        // DATA VAL
        int decimalNumber = Integer.parseInt(txtDecimal.getText());
        String binaryNumber = "";
        int remainder;
        while(decimalNumber != 1/2){
            remainder = decimalNumber % 2;
            decimalNumber = decimalNumber / 2;
            binaryNumber += Integer.toString(remainder);
        }
        System.out.println(binaryNumber);
    }//GEN-LAST:event_btnDecToBinActionPerformed

    private void btnDecToBin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecToBin1ActionPerformed
        String binaryNumber = txtBinary.getText();
        int decimalNumber = 0;
        double power = 0;
        for(int i = binaryNumber.length()-1; i >= 0; i--){
            
            int binaryNum = Character.getNumericValue(binaryNumber.charAt(i));
            int baseTwoNum = binaryNum * (int) Math.pow(2, power);
            decimalNumber += baseTwoNum;
            power+=1;
        }
        System.out.println(decimalNumber);
    }//GEN-LAST:event_btnDecToBin1ActionPerformed

    private void btnDecToBin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecToBin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDecToBin2ActionPerformed

    private void btnHextToDecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHextToDecActionPerformed
        String hexNumber = txtHexadecimal.getText();
        int decimalNumber = 0;
        double power = 0;
        char[] letterToHex = {'A'};
        int[] hexNumbersList = {11};
        for(int i = hexNumber.length()-1; i >= 0; i--){
            char currentLetter = hexNumber.charAt(i);
            if(new String(letterToHex).indexOf(currentLetter)){
                
            }
            int binaryNum = Character.getNumericValue(binaryNumber.charAt(i));
            int baseTwoNum = binaryNum * (int) Math.pow(2, power);
            decimalNumber += baseTwoNum;
            power+=1;
        }
        System.out.println(decimalNumber);
    }//GEN-LAST:event_btnHextToDecActionPerformed

    private void txtHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHexadecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHexadecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anwarAssignment26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anwarAssignment26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anwarAssignment26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anwarAssignment26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anwarAssignment26().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecToBin;
    private javax.swing.JButton btnDecToBin1;
    private javax.swing.JButton btnDecToBin2;
    private javax.swing.JButton btnHextToDec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtBinary;
    private javax.swing.JTextField txtDecimal;
    private javax.swing.JTextField txtHexadecimal;
    // End of variables declaration//GEN-END:variables
}
