
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author s201076699
 */
public class FrmDiceGame extends javax.swing.JFrame {
    final int EASY_MODE_HEALTH = 45;
    final int MEDIUM_MODE_HEALTH = 50;
    final int HARD_MODE_HEALTH = 55;
    final int GOD_MODE_HEALTH = 50;
    /* Initial health will only be set when the mode is changed, it keeps track 
    of the maximum health acheivable, in other words, the starting health*/
    int initialHealth = 20;
    // Initialized and set health counter to 20, this variable will change with each guess
    int health = 20;
    
    int totalRolls = 0; 
    int totalCorrect = 0; 
    int totalIncorrect = 0; 
    int userGuess; 
    int diceRoll; 
    int rollAmount = 6;
    double percCorrect = 0;
    
    // Creates new form FrmDiceGame
    public FrmDiceGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup5 = new javax.swing.ButtonGroup();
        lblCorrectValue = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPercentValue = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblIncorrectValue = new javax.swing.JLabel();
        lblRollsValue = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtUserGuess = new javax.swing.JTextField();
        featurePanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        radEasyMode = new javax.swing.JRadioButton();
        radMediumMode = new javax.swing.JRadioButton();
        radHardMode = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        lblHealthAmount = new javax.swing.JLabel();
        radGodMode = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        lblRollInstructions = new javax.swing.JLabel();
        btnRollDice = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCorrectAnswer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 200, 0));

        lblCorrectValue.setText("0");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Percentage of correct guesses:");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setText("Number of incorrect guesses:");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Number of correct guesses:");

        lblPercentValue.setText("0");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Number of rolls:");

        lblIncorrectValue.setText("0");

        lblRollsValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRollsValue.setText("0");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel14.setText("Dice Roll");

        jLabel15.setText("and click to roll the dice");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Super Dice Guessing Game");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel18.setText("Your Guess");

        txtUserGuess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUserGuess.setText("0");
        txtUserGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserGuessActionPerformed(evt);
            }
        });

        featurePanel.setBackground(new java.awt.Color(204, 204, 255));
        featurePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        featurePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Choose Difficulty:");

        radEasyMode.setBackground(featurePanel.getBackground());
        buttonGroup5.add(radEasyMode);
        radEasyMode.setSelected(true);
        radEasyMode.setText("Easy");
        radEasyMode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radEasyMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEasyModeActionPerformed(evt);
            }
        });

        radMediumMode.setBackground(featurePanel.getBackground());
        buttonGroup5.add(radMediumMode);
        radMediumMode.setText("Medium");
        radMediumMode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radMediumMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMediumModeActionPerformed(evt);
            }
        });

        radHardMode.setBackground(featurePanel.getBackground());
        buttonGroup5.add(radHardMode);
        radHardMode.setText("Hard");
        radHardMode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        radHardMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHardModeActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Life Amount");

        lblHealthAmount.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        lblHealthAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHealthAmount.setText("Health: 20");

        radGodMode.setBackground(new java.awt.Color(204, 0, 0));
        buttonGroup5.add(radGodMode);
        radGodMode.setForeground(new java.awt.Color(255, 255, 255));
        radGodMode.setText("God Mode");
        radGodMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radGodModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout featurePanelLayout = new javax.swing.GroupLayout(featurePanel);
        featurePanel.setLayout(featurePanelLayout);
        featurePanelLayout.setHorizontalGroup(
            featurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(featurePanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(featurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radEasyMode)
                    .addComponent(radMediumMode)
                    .addComponent(radHardMode)
                    .addComponent(radGodMode))
                .addContainerGap(65, Short.MAX_VALUE))
            .addComponent(lblHealthAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        featurePanelLayout.setVerticalGroup(
            featurePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(featurePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radEasyMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radMediumMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radHardMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radGodMode)
                .addGap(56, 56, 56)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHealthAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dice.png"))); // NOI18N

        lblRollInstructions.setText("Enter an amount from 1 to 6");

        btnRollDice.setText("Roll Dice");
        btnRollDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRollDiceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Correct Anwser:  ");

        lblCorrectAnswer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCorrectAnswer.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(featurePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(40, 40, 40)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(101, 101, 101)
                                            .addComponent(btnRollDice)))
                                    .addGap(63, 63, 63)
                                    .addComponent(lblRollsValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addGap(139, 139, 139)
                                    .addComponent(jLabel14)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(jLabel12))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(40, 40, 40))
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPercentValue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIncorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCorrectValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblRollInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97)
                        .addComponent(lblCorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(featurePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRollInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel14)
                                        .addGap(2, 2, 2))
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUserGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRollDice))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(lblRollsValue)))
                                .addGap(47, 47, 47)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(2, 2, 2)
                                .addComponent(lblCorrectValue)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblIncorrectValue, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(lblPercentValue))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblCorrectAnswer))
                                .addGap(46, 46, 46)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(115, 115, 115))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setMode(int rollingAmount, int healthAmount){
        rollAmount = rollingAmount;
        lblRollInstructions.setText("Enter a number from 1 to " + Integer.toString(rollingAmount));
        health = healthAmount;
    }
    void modifyHealth(String healthAction){
        if(health <= 0){
            lblHealthAmount.setText("Your health is being reset");
            health = initialHealth;
            
            // JavaScript has much better ways to do this, but this works just as well
            final ImageIcon icon = new ImageIcon("dice.png");
            JOptionPane.showMessageDialog(null, "You have died. Your life will be reset.", "Death Notification", JOptionPane.INFORMATION_MESSAGE, icon);
        } else if(healthAction.equals("remove")){
            health -=5;
            lblHealthAmount.setText("Health: " + Integer.toString(health));
        } else {
            health += 5;
            lblHealthAmount.setText("Health: " + Integer.toString(health));
        }
        /* Note: To avoid having the lblHealthAmount.setText line three times, 
           I could have nested if statements, but those look bad*/
    }
    
    private void txtUserGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserGuessActionPerformed
        
    }//GEN-LAST:event_txtUserGuessActionPerformed

    private void radEasyModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEasyModeActionPerformed
        setMode(6, EASY_MODE_HEALTH);
        initialHealth = EASY_MODE_HEALTH;
    }//GEN-LAST:event_radEasyModeActionPerformed

    private void radGodModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radGodModeActionPerformed
        // Health is set to 35 on purpose, it's called God Mode for a reason
        setMode(1000, GOD_MODE_HEALTH);
        initialHealth = GOD_MODE_HEALTH;
    }//GEN-LAST:event_radGodModeActionPerformed

    private void radMediumModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMediumModeActionPerformed
        setMode(40, MEDIUM_MODE_HEALTH);
        initialHealth = MEDIUM_MODE_HEALTH;
    }//GEN-LAST:event_radMediumModeActionPerformed

    private void radHardModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHardModeActionPerformed
        setMode(80, HARD_MODE_HEALTH);
        initialHealth = HARD_MODE_HEALTH;
    }//GEN-LAST:event_radHardModeActionPerformed

    private void btnRollDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRollDiceActionPerformed
        diceRoll = (int) Math.round (Math.random()*rollAmount+1);
        lblRollsValue.setText(String.valueOf(diceRoll));
        userGuess = Integer.parseInt(txtUserGuess.getText ());
        totalRolls = totalRolls + 1;
        
        if (diceRoll == userGuess){
            totalCorrect = totalCorrect + 1;
            modifyHealth("add");
        }
        else{
            totalIncorrect = totalIncorrect + 1;
            modifyHealth("remove");
        }
        
        percCorrect = ((double) totalCorrect/ (double) totalRolls) *100;
        percCorrect = percCorrect*100;
        percCorrect = Math.round(percCorrect);
        percCorrect = percCorrect / 100;
        lblCorrectAnswer.setText(Integer.toString(diceRoll));
        lblRollsValue.setText(String.valueOf(totalRolls));
        lblCorrectValue.setText(String.valueOf(totalCorrect));
        lblIncorrectValue.setText(String.valueOf(totalIncorrect));
        lblPercentValue.setText (String.valueOf(percCorrect));
    }//GEN-LAST:event_btnRollDiceActionPerformed
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDiceGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDiceGame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRollDice;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JPanel featurePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel lblCorrectAnswer;
    private javax.swing.JLabel lblCorrectValue;
    private javax.swing.JLabel lblHealthAmount;
    private javax.swing.JLabel lblIncorrectValue;
    private javax.swing.JLabel lblPercentValue;
    private javax.swing.JLabel lblRollInstructions;
    private javax.swing.JLabel lblRollsValue;
    private javax.swing.JRadioButton radEasyMode;
    private javax.swing.JRadioButton radGodMode;
    private javax.swing.JRadioButton radHardMode;
    private javax.swing.JRadioButton radMediumMode;
    private javax.swing.JTextField txtUserGuess;
    // End of variables declaration//GEN-END:variables
}
